services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sportverse-app
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - sportverse

  db:
    image: postgres:17
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: sportverse
      POSTGRES_USER: sportverse
      POSTGRES_PASSWORD: sportversesecret
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - sportverse

networks:
  sportverse:

volumes:
  pgdata:
